#!/usr/bin/env python3
"""Vendor Adafruit's 'classic' 5x7 font into the two places that need it.

The font is the one thing the C++ harness and the JS renderer must agree on
byte-for-byte, so both copies come out of one run of this script:

    tests/stubs/glcdfont.h    used by the host stub, so a fresh clone and CI
                              both work with no Arduino install
    preview/glcdfont.js       used by the browser and by the golden diff

Both outputs are committed. You only need to re-run this if you point it at a
different upstream font.

    python3 preview/tools/gen_font.py            # find the Arduino library
    python3 preview/tools/gen_font.py --check    # fail if the copies are stale
    python3 preview/tools/gen_font.py --src path/to/glcdfont.c
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]

# Where the Adafruit_GFX library normally lands. First hit wins.
CANDIDATES = [
    pathlib.Path.home() / "Documents/Arduino/libraries/Adafruit_GFX_Library/glcdfont.c",
    pathlib.Path.home() / "Library/Arduino15/libraries/Adafruit_GFX_Library/glcdfont.c",
    pathlib.Path("/usr/share/arduino/libraries/Adafruit_GFX_Library/glcdfont.c"),
]

GLYPHS = 256
COLS = 5  # 5 column-bytes per glyph, one bit per row, LSB = top row


def find_source(explicit):
    if explicit:
        p = pathlib.Path(explicit)
        if not p.is_file():
            sys.exit(f"no such file: {p}")
        return p
    for p in CANDIDATES:
        if p.is_file():
            return p
    sys.exit(
        "cannot find glcdfont.c. Install Adafruit_GFX_Library, or pass --src.\n"
        "The generated copies are committed, so you only need this to regenerate."
    )


def parse(src):
    """Pull the 1280 bytes of font data out of glcdfont.c."""
    text = src.read_text()
    # The file is one big `static const unsigned char font[] PROGMEM = { ... };`
    body = text[text.index("{", text.index("font[]")) :]
    body = body[: body.index("};")]
    vals = [int(m, 16) for m in re.findall(r"0[xX]([0-9a-fA-F]{2})", body)]
    want = GLYPHS * COLS
    if len(vals) != want:
        sys.exit(f"{src}: expected {want} bytes, parsed {len(vals)}")
    return vals


def emit_h(vals, src):
    rows = []
    for g in range(GLYPHS):
        cols = ", ".join(f"0x{v:02X}" for v in vals[g * COLS : (g + 1) * COLS])
        rows.append(f"    {cols},   // 0x{g:02X}")
    body = "\n".join(rows)
    return f"""// GENERATED by preview/tools/gen_font.py from {src.name} — do not edit by hand.
//
// Adafruit_GFX's 'classic' 5x7 font: 256 glyphs, 5 column-bytes each, one bit
// per row with the LSB at the top. Vendored so the host harness needs no
// Arduino install, and so preview/glcdfont.js cannot drift from it.
#ifndef GP_STUB_GLCDFONT_H
#define GP_STUB_GLCDFONT_H

#include <cstdint>

static const uint8_t gp_glcdfont[{GLYPHS} * {COLS}] = {{
{body}
}};

#endif  // GP_STUB_GLCDFONT_H
"""


def emit_js(vals, src):
    # 16 bytes a line keeps the diff readable and the file under 6 KB.
    lines = []
    for i in range(0, len(vals), 16):
        lines.append("  " + ", ".join(str(v) for v in vals[i : i + 16]) + ",")
    body = "\n".join(lines)
    return f"""// GENERATED by preview/tools/gen_font.py from {src.name} — do not edit by hand.
//
// Adafruit_GFX's 'classic' 5x7 font: 256 glyphs, 5 column-bytes each, one bit
// per row with the LSB at the top. The same bytes as tests/stubs/glcdfont.h,
// which is what lets the JS renderer match the C++ one exactly.
export const FONT = new Uint8Array([
{body}
]);

export const FONT_GLYPHS = {GLYPHS};
export const FONT_COLS = {COLS};
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", help="path to glcdfont.c")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated files are out of date")
    args = ap.parse_args()

    src = find_source(args.src)
    vals = parse(src)

    outputs = {
        ROOT / "tests/stubs/glcdfont.h": emit_h(vals, src),
        ROOT / "preview/glcdfont.js": emit_js(vals, src),
    }

    stale = []
    for path, want in outputs.items():
        have = path.read_text() if path.is_file() else None
        if have == want:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(want)

    if args.check:
        if stale:
            for p in stale:
                print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
            print("run: python3 preview/tools/gen_font.py", file=sys.stderr)
            return 1
        print(f"font up to date ({len(vals)} bytes)")
        return 0

    for p in stale:
        print(f"wrote {p.relative_to(ROOT)}")
    if not stale:
        print("font already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
