#!/usr/bin/env python3
"""firmware/gasprices/layout.json -> firmware/gasprices/layout.h

The generated header is plain `static const` structs, so ui.h reads L_price.x
where it used to have the literal 6, at no runtime cost and with no loss of
readability.

    python3 preview/tools/gen_layout.py            # regenerate layout.h
    python3 preview/tools/gen_layout.py --check     # fail if it is out of date

--check runs in CI. Without it, a hand-edit of layout.h would silently outrank
layout.json and the browser preview would start disagreeing with the panel for a
reason nobody could see.
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "firmware/gasprices/layout.json"
DST = ROOT / "firmware/gasprices/layout.h"

# The fields that become C. Anything else in layout.json (note, anchor) is there
# for humans and for the editor, and is deliberately not emitted: see the header
# comment in layout.json for why colours and visibility stay in ui.h.
FIELDS = ["x", "y", "w", "h", "size", "dot_r"]


def emit(layout):
    panel = layout["panel"]
    rows = []
    width = max(len(n) for n in layout["elements"])
    for name, el in layout["elements"].items():
        vals = ", ".join(f"{el.get(f, 0):>3}" for f in FIELDS)
        note = el.get("note", "")
        rows.append(f"static const GpElem L_{name:<{width}} = {{ {vals} }};"
                    + (f"  // {note}" if note else ""))
    body = "\n".join(rows)
    fields = ", ".join(FIELDS)

    return f"""// GENERATED by preview/tools/gen_layout.py from layout.json — do not edit by hand.
//
// Edit layout.json instead, then re-run the generator — or drag the element in
// the browser preview, which does both for you. `gen_layout.py --check` runs in
// CI and fails if this file and layout.json have drifted apart.
//
// Fields an element has no use for are 0: a right-aligned label has no w/h, a
// rule has no size. Anchoring, visibility rules and colours are ui.h's job.
#ifndef GP_LAYOUT_H
#define GP_LAYOUT_H

#include <stdint.h>

#define L_PANEL_W {panel["w"]}
#define L_PANEL_H {panel["h"]}

typedef struct {{ int16_t {fields}; }} GpElem;

{body}

#endif  // GP_LAYOUT_H
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if layout.h is out of date")
    args = ap.parse_args()

    if not SRC.is_file():
        sys.exit(f"missing {SRC.relative_to(ROOT)}")

    layout = json.loads(SRC.read_text())
    for key in ("panel", "elements"):
        if key not in layout:
            sys.exit(f"{SRC.name}: no \"{key}\" key")
    unknown = {f for el in layout["elements"].values() for f in el} \
        - set(FIELDS) - {"note", "anchor"}
    if unknown:
        sys.exit(f"{SRC.name}: unknown field(s) {sorted(unknown)}; "
                 f"known geometry fields are {FIELDS}")

    want = emit(layout)
    have = DST.read_text() if DST.is_file() else None

    if args.check:
        if have == want:
            print(f"{DST.relative_to(ROOT)} is in sync with layout.json")
            return 0
        print(f"{DST.relative_to(ROOT)} is out of date", file=sys.stderr)
        print("run: python3 preview/tools/gen_layout.py", file=sys.stderr)
        return 1

    if have == want:
        print(f"{DST.relative_to(ROOT)} already up to date")
        return 0
    DST.write_text(want)
    print(f"wrote {DST.relative_to(ROOT)} "
          f"({len(layout['elements'])} elements)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
