// GENERATED by preview/tools/gen_layout.py from layout.json — do not edit by hand.
//
// Edit layout.json instead, then re-run the generator — or drag the element in
// the browser preview, which does both for you. `gen_layout.py --check` runs in
// CI and fails if this file and layout.json have drifted apart.
//
// Fields an element has no use for are 0: a right-aligned label has no w/h, a
// rule has no size. Anchoring, visibility rules and colours are ui.h's job.
#ifndef GP_LAYOUT_H
#define GP_LAYOUT_H

#include <stdint.h>

#define L_PANEL_W 320
#define L_PANEL_H 172

typedef struct { int16_t x, y, w, h, size, dot_r; } GpElem;

static const GpElem L_header         = {  11,   2,   0,   0,   1,   0 };  // station label, rank, and the cheapest / vs-best tag
static const GpElem L_age            = { 309,   2,   0,   0,   1,   0 };  // hours since the feed updated, or OFF
static const GpElem L_divider        = {   0,  14, 320,   0,   0,   0 };  // rule under the header
static const GpElem L_price          = {  11,  22,   0,   0,   4,   0 };  // today's price at the station on screen
static const GpElem L_level_text     = { 309,  24,   0,   0,   2,   0 };  // LVL nn%
static const GpElem L_level_bar      = { 170,  46, 139,  12,   0,   0 };  // outline plus a proportional fill
static const GpElem L_verdict_bar    = {   0,  62, 320,  38,   0,   0 };  // full-width band in the verdict colour
static const GpElem L_verdict_text   = {   0,  69,   0,   0,   3,   0 };  // centred in the bar
static const GpElem L_reason         = {  11, 106,   0,   0,   2,   0 };  // one line of plain English, 21 chars max at size 2
static const GpElem L_tank           = {  11, 126,   0,   0,   1,   0 };  // TANK FULL / HALF / LOW
static const GpElem L_savings        = { 309, 126,   0,   0,   1,   0 };  // SAVE n.nc, USUAL, +n.nc, or the wait countdown
static const GpElem L_sparkline      = {  11, 138, 298,  30,   0,   2 };  // rolling window, with a fat dot on today
static const GpElem L_message_title  = {   0,  58,   0,   0,   3,   0 };  // boot and hard-failure screen, centred
static const GpElem L_message_detail = {   0,  96,   0,   0,   2,   0 };  // second line of the same screen, centred

#endif  // GP_LAYOUT_H
